// text
const text = [
  ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus, odio! Quae voluptates nobis architecto odio beatae veritatis esse voluptas eius, magni, id blanditiis impedit. Saepe, ea beatae quam molestias, adipisci aspernatur quod provident mollitia incidunt amet dolorem reiciendis voluptas. Tempora reprehenderit inventore numquam eos saepe ea distinctio quia ex optio alias! Illum veniam praesentium aut error vero tempore earum voluptatem provident, alias eos maiores modi dolorem quidem adipisci aliquid incidunt non repellat voluptas aspernatur hic? Dicta atque aliquam veritatis cumque tenetur, officiis necessitatibus culpa asperiores totam corporis facere amet suscipit aut quasi ratione similique commodi. Quo tempora repellendus illum obcaecati tempore, magni fugiat rerum at totam nulla unde, quos, ducimus recusandae quas! Dolorem voluptate aliquid hic illum dignissimos iste! Perspiciatis `,
  `deserunt facilis accusamus quas, consectetur deleniti aut hic illum modi veniam minima vero, mollitia non cupiditate corporis odit numquam distinctio eligendi alias tempora temporibus laborum? Ab, alias vel. Possimus exercitationem praesentium quam excepturi rerum dolor odit veniam labore, eum modi provident numquam nostrum alias aperiam accusantium quaerat, eos ratione earum animi illo. Nihil fugiat delectus magni error recusandae sequi soluta blanditiis voluptatibus dolorem aperiam iusto rerum maiores excepturi sunt, quibusdam in commodi quasi velit accusamus quisquam quos eligendi nostrum. Dolorem, consequuntur magnam officiis nam quisquam architecto culpa illum, autem doloremque ab libero molestias blanditiis eaque minus labore dignissimos. Vero ipsam culpa tenetur autem eos eum alias at iure nemo? Harum placeat sit `,
  `exercitationem reiciendis? Animi, earum accusamus neque odio ipsam recusandae eligendi, quae, totam eveniet facere maiores sit nam nemo culpa eius aut saepe praesentium! Dolorum ab inventore molestiae? Recusandae ducimus sed repudiandae neque possimus, libero amet optio vero magnam at cumque obcaecati, omnis velit veniam. Aliquam ullam cum maiores provident iure eum, non at, odio minus necessitatibus praesentium dolor exercitationem porro officiis ab iusto vero minima dignissimos. Modi excepturi perspiciatis officia, delectus odit qui itaque saepe magnam laborum hic molestias exercitationem, pariatur recusandae quo ipsum. Nisi odio porro laboriosam dolorum repellat debitis illum suscipit commodi delectus, pariatur dolorem fugit similique soluta, nihil doloremque, aliquam nobis quam quae itaque voluptatum necessitatibus omnis molestias harum! Voluptatibus modi harum sit quos dolores reprehenderit autem, voluptatum corporis est tenetur reiciendis nobis quo, culpa voluptatem? Ullam sed dignissimos inventore hic sunt rem, quam omnis perspiciatis fugit voluptatem, labore at alias rerum odit aspernatur, molestias voluptas minus? Rerum quis tempore ea! Dolorum repellat voluptates alias cumque architecto est maiores sint temporibus, doloribus rem veritatis cum beatae sed rerum `,
  `corporis maxime? Voluptates, assumenda suscipit, non sapiente quam minima reiciendis molestiae harum perferendis velit architecto eum atque odio ad mollitia omnis ipsam alias! Iusto consectetur quas eos, eius dolore aliquid, tenetur laborum esse obcaecati provident rerum commodi ut, explicabo iste fugiat error quia. Dicta voluptate assumenda molestiae natus velit nulla iusto, soluta nemo sunt consequuntur ab ducimus, impedit explicabo? Culpa, nobis blanditiis? Dolores esse deleniti tempore quos, voluptatum soluta necessitatibus accusantium deserunt sequi ab quis accusamus possimus ipsa dolor minus animi labore nam, placeat aut at. Maxime aut dicta fugiat consequuntur illo quam recusandae ab, placeat, sit doloremque sunt laborum facilis sint commodi`,
  `similique omnis quos pariatur? Obcaecati, fuga voluptates. Aut at, aspernatur ipsam odit, quas debitis natus expedita eaque libero eveniet illo! Vitae nam officia voluptatibus omnis? Itaque perspiciatis ex delectus? Eum, minus ipsum dicta esse pariatur eligendi similique nisi. Provident magni adipisci nihil nostrum ratione modi, sed eaque dicta enim, deserunt id sint? Voluptatum impedit quia vero quasi ratione alias facere non dicta libero praesentium, distinctio perferendis amet harum sequi temporibus aliquid tempora consequatur adipisci nostrum nemo officia accusamus debitis. Sed illum reiciendis exercitationem id facere unde eum totam consectetur molestias soluta, dignissimos, libero, laboriosam laborum asperiores accusantium voluptatum facilis numquam eligendi! Voluptate amet culpa blanditiis quisquam, eaque vel minima eligendi, consectetur fugit labore, a facilis accusamus cum doloribus? At fugiat quas minus asperiores doloremque possimus dicta accusamus `,
  `laboriosam dolorum quos labore esse dolores omnis eligendi, voluptatibus autem molestias itaque reprehenderit sint? Cumque ab quisquam officiis, officia illo aspernatur dolor deleniti incidunt non maiores assumenda expedita minima repellat nisi, corrupti accusamus dicta! Alias libero vitae sit, corrupti numquam adipisci similique possimus, quis, unde repudiandae dolor et quos. Eum, odio consectetur voluptatem quidem quod omnis eaque cumque nisi magnam maxime saepe nam consequuntur consequatur soluta tempore quos neque, quam corrupti excepturi impedit, provident temporibus mollitia. Quo, optio. Sed fugit delectus, consequatur recusandae architecto numquam quod debitis impedit molestiae minima itaque officiis amet assumenda quia cum corporis? Itaque tenetur suscipit officia cumque quaerat harum autem! Dignissimos vitae maiores suscipit `,
  ` dolores voluptate illo recusandae facilis voluptates, laboriosam voluptatibus animi ea iste magnam dolorem, itaque impedit, error nesciunt libero corrupti corporis? Dolorum iusto atque accusamus assumenda, iste cum incidunt aliquam! Molestiae, iure? Ipsam, quas dicta. Ab corporis voluptatibus molestias? Mollitia aperiam molestiae dolorum pariatur ipsum inventore ut unde voluptatum quidem nulla. Nisi nesciunt rem temporibus repellendus. Cum autem vitae minus ea dolorem alias aspernatur, sit perferendis quibusdam ut incidunt amet ullam atque officia doloremque modi numquam excepturi non eligendi saepe. Nemo praesentium, aspernatur dicta dolorum quo vero eos nostrum porro animi recusandae `,
  `assumenda ipsa similique, eligendi quidem iusto sequi! Illo eius excepturi quo nemo architecto eaque qui dolorum quasi officia, commodi reprehenderit animi magni adipisci ipsa suscipit id fugit laudantium culpa aperiam tenetur? Quibusdam, ad? Quasi nesciunt quia amet, quisquam, quo qui saepe quibusdam beatae incidunt excepturi officia optio facere voluptates possimus deleniti unde consectetur nemo ipsa esse modi. Vel, laborum nobis? Eligendi corporis officia labore iusto maxime quae ullam consequatur fuga? Aspernatur ullam mollitia similique assumenda nobis deserunt alias eum facere quod tempora hic dolor perspiciatis omnis id vitae reiciendis iure obcaecati voluptatibus vel velit ex exercitationem, asperiores voluptatem. Excepturi laboriosam quis eligendi atque molestiae repellat `,
  `vero saepe! Eveniet excepturi dignissimos deleniti eius eos error omnis, adipisci numquam ipsum, dolorem facere laboriosam porro tempora accusamus doloribus, consectetur ipsam eaque. Sapiente, blanditiis consequuntur, numquam ipsum consequatur aspernatur enim itaque doloremque assumenda ex ut porro quidem dolor adipisci ducimus perspiciatis architecto accusamus magnam? Culpa quisquam illum dolorem blanditiis nulla non eligendi iure minus doloribus sint, nihil, aspernatur maiores laudantium iste assumenda eos maxime, excepturi consectetur iusto hic praesentium delectus. Asperiores deserunt minus optio pariatur repellat fugiat nisi, culpa officiis natus ratione, velit harum ex cum exercitationem tempore obcaecati veritatis ipsa iusto. Possimus in soluta minus laboriosam delectus eos, eius iste iusto, sequi `,
];

const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const result = document.querySelector(".lorem-text");

form.addEventListener("submit", function (e) {
  e.preventDefault();
  const value = parseInt(amount.value);
  const random = Math.floor(Math.random() * text.length);
  //   console.log(value);
  //   console.log(isNaN(value));
  if (isNaN(value) || value <= 0 || value > 9) {
    result.innerHTML = `<p class="result">${text[random]}</p>`;
  } else {
    let tempText = text.slice(0, value);
    // console.log(tempText);
    tempText = tempText
      .map(function (para) {
        return `<p class="result">${para}</p>`;
      })
      .join("");
    //   console.log(tempText);
    result.innerHTML = tempText;
  }
});
